/**
 * Custom Cloudflare Worker entry for OpenNext.
 * Re-uses the generated fetch handler and adds a native `scheduled()` cron entry.
 *
 * Docs: https://opennext.js.org/cloudflare/howtos/custom-worker
 *
 * Local test:
 *   wrangler dev --test-scheduled
 *   curl "http://localhost:8787/__scheduled?cron=0+*+*+*+*"
 */

// Generated by `opennextjs-cloudflare build` — present at deploy/build time.
// @ts-expect-error .open-next/worker.js is produced by cf:build
import { default as handler } from "./.open-next/worker.js";

import { applyWorkerEnv } from "./lib/background/client";
import { runBackgroundJobs } from "./lib/background/runBackgroundJobs";

type ScheduledEvent = { cron: string; scheduledTime: number };
type WorkerEnv = CloudflareEnv & Record<string, unknown>;
type WorkerCtx = { waitUntil: (promise: Promise<unknown>) => void };

const worker = {
  fetch: handler.fetch,

  async scheduled(controller: ScheduledEvent, env: WorkerEnv, ctx: WorkerCtx) {
    applyWorkerEnv(env);

    ctx.waitUntil(
      runBackgroundJobs({
        source: "cloudflare_cron",
        cron: controller.cron,
        scheduledTime: controller.scheduledTime,
      }).catch((error) => {
        console.error(
          "[worker.scheduled]",
          error instanceof Error ? error.message : "background_jobs_failed",
        );
      }),
    );
  },
};

export default worker;

// Required when OpenNext DO cache features are enabled (safe no-op exports otherwise).
// @ts-expect-error .open-next/worker.js is produced by cf:build
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
