import type { KnowledgeModule } from "@/lib/assistant/knowledge/types";

export const ADMIN_MODULES: KnowledgeModule[] = [
  {
    key: "admin-dashboard",
    title: "Admin Dashboard",
    titleEn: "Admin Dashboard",
    route: "/admin",
    description: "Rezumat operațional al platformei: semnale, health și acces rapid la module.",
    descriptionEn: "Platform ops overview: signals, health, and quick links.",
    actions: ["Deschide modulele admin", "Verifică health"],
    actionsEn: ["Open admin modules", "Check health"],
    permissions: ["dashboard.read"],
    relatedModules: ["admin-health", "admin-errors"],
    keywords: ["admin", "dashboard", "platform"],
    suggestedQuestions: ["Ce pot face aici?", "Unde văd erorile?"],
    suggestedQuestionsEn: ["What can I do here?", "Where are errors?"],
  },
  {
    key: "admin-users",
    title: "Utilizatori",
    titleEn: "Users",
    route: "/admin/users",
    description: "Listă și inspecție read-only a utilizatorilor platformei.",
    descriptionEn: "List and inspect platform users (read-oriented).",
    actions: ["Caută utilizator", "Deschide profilul"],
    actionsEn: ["Search user", "Open profile"],
    permissions: ["users.read"],
    relatedModules: ["admin-workspaces", "admin-audit"],
    keywords: ["users", "utilizatori", "cont", "user"],
    suggestedQuestions: ["Cum găsesc un utilizator?", "Ce pot vedea despre un user?"],
    suggestedQuestionsEn: ["How do I find a user?", "What can I see about a user?"],
  },
  {
    key: "admin-workspaces",
    title: "Workspace-uri",
    titleEn: "Workspaces",
    route: "/admin/workspaces",
    description:
      "Listă workspace-uri, inspect read-only, suspendare (dacă ai drept) și context de plan.",
    descriptionEn: "List workspaces, read-only inspect, suspend (if allowed), plan context.",
    actions: ["Inspectează workspace", "Suspendă workspace", "Vezi abonamentul"],
    actionsEn: ["Inspect workspace", "Suspend workspace", "View subscription"],
    permissions: ["workspaces.read", "workspaces.write"],
    relatedModules: ["admin-subscriptions", "admin-plans"],
    keywords: ["workspace", "workspaces", "suspend", "inspect"],
    suggestedQuestions: [
      "Cum inspectez un workspace?",
      "Cum suspend un workspace?",
      "Cum schimb planul?",
    ],
    suggestedQuestionsEn: [
      "How do I inspect a workspace?",
      "How do I suspend a workspace?",
      "How do I change the plan?",
    ],
  },
  {
    key: "admin-subscriptions",
    title: "Abonamente",
    titleEn: "Subscriptions",
    route: "/admin/subscriptions",
    description: "Starea abonamentelor workspace (plan, status Stripe/manual).",
    descriptionEn: "Workspace subscription status (plan, Stripe/manual).",
    actions: ["Vezi abonamente", "Deschide detalii"],
    actionsEn: ["View subscriptions", "Open details"],
    permissions: ["subscriptions.read"],
    relatedModules: ["admin-plans", "admin-workspaces"],
    keywords: ["subscription", "abonament", "stripe", "plan"],
    suggestedQuestions: ["Ce statusuri au abonamentele?"],
    suggestedQuestionsEn: ["What subscription statuses exist?"],
  },
  {
    key: "admin-plans",
    title: "Planuri",
    titleEn: "Plans",
    route: "/admin/plans",
    description: "Catalog Free/Solo/Studio/Agency și versiuni de preț.",
    descriptionEn: "Free/Solo/Studio/Agency catalog and price versions.",
    actions: ["Vezi planuri", "Editează (dacă ai drept)"],
    actionsEn: ["View plans", "Edit (if allowed)"],
    permissions: ["plans.read", "plans.write"],
    relatedModules: ["admin-subscriptions"],
    keywords: ["plans", "planuri", "free", "solo", "studio", "agency"],
    suggestedQuestions: ["Ce diferențiază Studio de Solo?"],
    suggestedQuestionsEn: ["What differs Studio from Solo?"],
  },
  {
    key: "admin-email-deliveries",
    title: "Email deliveries",
    titleEn: "Email deliveries",
    route: "/admin/email-deliveries",
    description: "Istoric livrări email (status, erori, destinatari).",
    descriptionEn: "Email delivery history (status, errors, recipients).",
    actions: ["Filtrează livrări", "Investighează eșecuri"],
    actionsEn: ["Filter deliveries", "Investigate failures"],
    permissions: ["emails.read"],
    relatedModules: ["admin-emails", "admin-errors"],
    keywords: ["email", "delivery", "livrare", "resend"],
    suggestedQuestions: ["Unde văd emailurile eșuate?"],
    suggestedQuestionsEn: ["Where do I see failed emails?"],
  },
  {
    key: "admin-emails",
    title: "Emailuri",
    titleEn: "Emails",
    route: "/admin/emails",
    description: "Operațiuni și template-uri email la nivel de platformă.",
    descriptionEn: "Platform-level email operations and templates.",
    actions: ["Vezi emailuri platformă"],
    actionsEn: ["View platform emails"],
    permissions: ["emails.read"],
    relatedModules: ["admin-email-deliveries"],
    keywords: ["emails", "emailuri", "template email"],
    suggestedQuestions: ["Ce văd în Emailuri?"],
    suggestedQuestionsEn: ["What is under Emails?"],
  },
  {
    key: "admin-cron",
    title: "Cron",
    titleEn: "Cron",
    route: "/admin/cron",
    description:
      "Rulează job-uri programate (automatizări, remindere). Cron-ul Cloudflare apelează workerul orar; există și endpoint HTTP protejat cu CRON_SECRET.",
    descriptionEn:
      "Scheduled jobs (automations, reminders). Cloudflare cron hits the worker hourly; HTTP fallback uses CRON_SECRET.",
    actions: ["Vezi rulări cron", "Înțelege schedule-ul"],
    actionsEn: ["View cron runs", "Understand schedule"],
    permissions: ["cron.read"],
    relatedModules: ["admin-jobs", "admin-webhooks"],
    keywords: ["cron", "schedule", "programat", "orar"],
    suggestedQuestions: ["Cum funcționează cronul?", "Ce rulează automat?"],
    suggestedQuestionsEn: ["How does cron work?", "What runs automatically?"],
  },
  {
    key: "admin-jobs",
    title: "Jobs",
    titleEn: "Jobs",
    route: "/admin/jobs",
    description: "Job-uri de fundal: status, erori, reîncercări.",
    descriptionEn: "Background jobs: status, errors, retries.",
    actions: ["Vezi job-uri", "Investighează eșecuri"],
    actionsEn: ["View jobs", "Investigate failures"],
    permissions: ["cron.read"],
    relatedModules: ["admin-cron", "admin-errors"],
    keywords: ["jobs", "background", "queue"],
    suggestedQuestions: ["Ce înseamnă un job eșuat?"],
    suggestedQuestionsEn: ["What does a failed job mean?"],
  },
  {
    key: "admin-webhooks",
    title: "Webhook-uri",
    titleEn: "Webhooks",
    route: "/admin/webhooks",
    description:
      "Evenimente webhook (ex. Stripe): recepție, semnătură, procesare. Nu expune secretele.",
    descriptionEn: "Webhook events (e.g. Stripe): receive, verify, process. Never expose secrets.",
    actions: ["Vezi evenimente", "Verifică procesarea"],
    actionsEn: ["View events", "Check processing"],
    permissions: ["webhooks.read"],
    relatedModules: ["admin-subscriptions", "admin-errors"],
    keywords: ["webhook", "stripe", "semnătură", "endpoint"],
    suggestedQuestions: ["Ce înseamnă un webhook?", "Cum văd evenimentele Stripe?"],
    suggestedQuestionsEn: ["What is a webhook?", "How do I see Stripe events?"],
  },
  {
    key: "admin-feedback",
    title: "Feedback",
    titleEn: "Feedback",
    route: "/admin/feedback",
    description: "Feedback utilizatori + semnale asistent (module confuze, thumbs down).",
    descriptionEn: "User feedback plus assistant signals (confusing modules, thumbs down).",
    actions: ["Triage feedback", "Vezi semnale asistent"],
    actionsEn: ["Triage feedback", "View assistant signals"],
    permissions: ["feedback.read"],
    relatedModules: ["admin-audit"],
    keywords: ["feedback", "util", "thumbs", "asistent"],
    suggestedQuestions: ["Cum triăm feedback-ul?"],
    suggestedQuestionsEn: ["How do we triage feedback?"],
  },
  {
    key: "admin-audit",
    title: "Audit",
    titleEn: "Audit",
    route: "/admin/audit",
    description: "Jurnal de acțiuni platformă (cine / ce / când) — fără date comerciale brute.",
    descriptionEn: "Platform action log (who/what/when) — no raw commercial payloads.",
    actions: ["Filtrează audit"],
    actionsEn: ["Filter audit"],
    permissions: ["audit.read"],
    relatedModules: ["admin-admins", "admin-workspaces"],
    keywords: ["audit", "log", "istoric"],
    suggestedQuestions: ["Ce văd în audit?"],
    suggestedQuestionsEn: ["What is in the audit log?"],
  },
  {
    key: "admin-system",
    title: "System",
    titleEn: "System",
    route: "/admin/settings",
    description: "Configurări platformă (ex. maintenance, registration).",
    descriptionEn: "Platform settings (e.g. maintenance, registration).",
    actions: ["Vezi setări platformă"],
    actionsEn: ["View platform settings"],
    permissions: ["settings.read", "system.read"],
    relatedModules: ["admin-health", "admin-errors"],
    keywords: ["system", "settings", "configurări", "maintenance"],
    suggestedQuestions: ["Ce setări de platformă există?"],
    suggestedQuestionsEn: ["What platform settings exist?"],
  },
  {
    key: "admin-health",
    title: "Health",
    titleEn: "Health",
    route: "/admin/system/health",
    description: "Starea serviciilor (Supabase, email, stripe etc.) pentru operațiuni.",
    descriptionEn: "Service health (Supabase, email, stripe) for ops.",
    actions: ["Verifică health"],
    actionsEn: ["Check health"],
    permissions: ["system.read"],
    relatedModules: ["admin-errors", "admin-cron"],
    keywords: ["health", "status", "uptime"],
    suggestedQuestions: ["Cum verific dacă platforma e healthy?"],
    suggestedQuestionsEn: ["How do I check platform health?"],
  },
  {
    key: "admin-errors",
    title: "Erori sistem",
    titleEn: "System errors",
    route: "/admin/system/errors",
    description: "Erori agregate pentru depanare — fără a expune secrete.",
    descriptionEn: "Aggregated errors for debugging — never expose secrets.",
    actions: ["Vezi erori recente"],
    actionsEn: ["View recent errors"],
    permissions: ["system.read"],
    relatedModules: ["admin-health", "admin-jobs"],
    keywords: ["errors", "erori", "exception", "bug"],
    suggestedQuestions: ["Unde văd erorile recente?"],
    suggestedQuestionsEn: ["Where are recent errors?"],
  },
  {
    key: "admin-admins",
    title: "Administratori",
    titleEn: "Administrators",
    route: "/admin/admins",
    description: "Roluri platformă (super admin, support, billing etc.).",
    descriptionEn: "Platform roles (super admin, support, billing, etc.).",
    actions: ["Vezi administratori", "Gestionează roluri (super admin)"],
    actionsEn: ["View admins", "Manage roles (super admin)"],
    permissions: ["admins.read"],
    relatedModules: ["admin-audit"],
    keywords: ["admins", "administratori", "rol platformă"],
    suggestedQuestions: ["Ce roluri de admin există?"],
    suggestedQuestionsEn: ["What admin roles exist?"],
  },
];
