import type { KnowledgeModule } from "@/lib/assistant/knowledge/types";

export const DASHBOARD_MODULES: KnowledgeModule[] = [
  {
    key: "dashboard",
    title: "Dashboard",
    titleEn: "Dashboard",
    route: "/dashboard",
    description:
      "Privire de ansamblu asupra leadurilor, evenimentelor, task-urilor și indicatorilor din workspace.",
    descriptionEn: "Overview of leads, events, tasks, and workspace indicators.",
    actions: ["Vezi rezumatul zilei", "Deschide modulele din meniu"],
    actionsEn: ["View daily summary", "Open modules from the menu"],
    permissions: ["crm.read"],
    relatedModules: ["leads", "calendar", "tasks", "analytics"],
    keywords: ["dashboard", "acasă", "home", "overview", "rezumat"],
    suggestedQuestions: [
      "Ce pot face aici?",
      "Unde văd leadurile?",
      "Unde găsesc analytics?",
    ],
    suggestedQuestionsEn: [
      "What can I do here?",
      "Where are leads?",
      "Where is analytics?",
    ],
  },
  {
    key: "leads",
    title: "Leaduri",
    titleEn: "Leads",
    route: "/dashboard/leads",
    description:
      "Pipeline de leaduri: creezi, filtrezi, actualizezi statusuri și convertești leaduri în clienți.",
    descriptionEn:
      "Lead pipeline: create, filter, update statuses, and convert leads to clients.",
    actions: [
      "Creează un lead",
      "Actualizează statusul",
      "Filtrează după sursă/status",
      "Convertește lead în client",
    ],
    actionsEn: [
      "Create a lead",
      "Update status",
      "Filter by source/status",
      "Convert lead to client",
    ],
    permissions: ["crm.read", "crm.write"],
    relatedModules: ["clients", "proposals", "automations"],
    keywords: [
      "lead",
      "leaduri",
      "pipeline",
      "conversie",
      "status",
      "filtru",
      "creează lead",
    ],
    suggestedQuestions: [
      "Cum creez un lead?",
      "Cum îl convertesc?",
      "Ce înseamnă statusurile?",
      "Cum folosesc filtrele?",
    ],
    suggestedQuestionsEn: [
      "How do I create a lead?",
      "How do I convert it?",
      "What do statuses mean?",
      "How do filters work?",
    ],
  },
  {
    key: "clients",
    title: "Clienți",
    titleEn: "Clients",
    route: "/dashboard/clients",
    description:
      "Dosare de clienți cu istoric de oferte, contracte, plăți și proiecte.",
    descriptionEn: "Client records with proposals, contracts, payments, and projects.",
    actions: ["Deschide dosarul clientului", "Editează datele", "Șterge client (dacă ai drept)"],
    actionsEn: ["Open client file", "Edit details", "Delete client (if allowed)"],
    permissions: ["crm.read", "crm.write", "crm.delete"],
    relatedModules: ["leads", "proposals", "contracts", "payments"],
    keywords: ["client", "clienți", "dosar", "contact", "șterge client"],
    suggestedQuestions: [
      "Cum transform un lead în client?",
      "Ce văd în dosarul clientului?",
      "De ce nu pot șterge clientul?",
    ],
    suggestedQuestionsEn: [
      "How do I turn a lead into a client?",
      "What is in the client file?",
      "Why can't I delete a client?",
    ],
  },
  {
    key: "proposals",
    title: "Oferte",
    titleEn: "Proposals",
    route: "/dashboard/proposals",
    description:
      "Creezi oferte cu pachete, le publici pe link public și urmărești vizualizarea/acceptarea.",
    descriptionEn:
      "Create package proposals, publish a public link, and track views/acceptance.",
    actions: ["Creează ofertă", "Publică oferta", "Deschide linkul public", "Vezi statusul"],
    actionsEn: ["Create proposal", "Publish proposal", "Open public link", "Check status"],
    permissions: ["proposals.write", "crm.read"],
    relatedModules: ["leads", "clients", "contracts"],
    keywords: ["ofertă", "oferte", "proposal", "publică", "acceptare", "pachet"],
    suggestedQuestions: [
      "Cum creez o ofertă?",
      "Cum public oferta?",
      "Ce se întâmplă după acceptare?",
    ],
    suggestedQuestionsEn: [
      "How do I create a proposal?",
      "How do I publish it?",
      "What happens after acceptance?",
    ],
  },
  {
    key: "contracts",
    title: "Contracte",
    titleEn: "Contracts",
    route: "/dashboard/contracts",
    description:
      "Draft, editare, publicare, acceptare digitală, PDF și creare proiect din contract.",
    descriptionEn:
      "Draft, edit, publish, digital acceptance, PDF, and create project from contract.",
    actions: [
      "Creează contract",
      "Editează draft",
      "Publică contractul",
      "Creează versiune",
      "Generează PDF",
      "Creează proiect din contract",
    ],
    actionsEn: [
      "Create contract",
      "Edit draft",
      "Publish contract",
      "Create version",
      "Generate PDF",
      "Create project from contract",
    ],
    permissions: ["contracts.write", "contracts.delete"],
    relatedModules: ["proposals", "payments", "projects", "templates"],
    keywords: [
      "contract",
      "contracte",
      "draft",
      "publică",
      "versiune",
      "pdf",
      "editare",
    ],
    suggestedQuestions: [
      "Cum creez contract?",
      "Ce înseamnă draft?",
      "Cum îl public?",
      "Cum creez versiune nouă?",
    ],
    suggestedQuestionsEn: [
      "How do I create a contract?",
      "What does draft mean?",
      "How do I publish it?",
      "How do I create a new version?",
    ],
    pageHints: [
      "Pe /dashboard/contracts/[id]/edit poți modifica doar un contract în status draft: conținut, clauze, termeni. După publicare, editarea se face prin versiune nouă.",
    ],
  },
  {
    key: "calendar",
    title: "Calendar",
    titleEn: "Calendar",
    route: "/dashboard/calendar",
    description: "Evenimente, întâlniri, deadline-uri și task-uri într-o vedere unificată.",
    descriptionEn: "Events, meetings, deadlines, and tasks in one view.",
    actions: ["Vezi evenimentele", "Deschide un eveniment", "Urmărește deadline-urile"],
    actionsEn: ["View events", "Open an event", "Track deadlines"],
    permissions: ["calendar.write", "crm.read"],
    relatedModules: ["projects", "tasks", "payments"],
    keywords: ["calendar", "eveniment", "întâlnire", "deadline", "dată"],
    suggestedQuestions: ["Ce văd în calendar?", "Cum leg un eveniment de proiect?"],
    suggestedQuestionsEn: ["What do I see in the calendar?", "How do I link an event to a project?"],
  },
  {
    key: "projects",
    title: "Proiecte",
    titleEn: "Projects",
    route: "/dashboard/projects",
    description:
      "Workflow pe tip de business, etape, echipă și checklist până la livrare.",
    descriptionEn: "Business-type workflow, stages, team, and checklist through delivery.",
    actions: ["Creează proiect", "Actualizează etapa", "Deschide checklist", "Creează din contract"],
    actionsEn: ["Create project", "Update stage", "Open checklist", "Create from contract"],
    permissions: ["projects.write", "projects.delete"],
    relatedModules: ["contracts", "tasks", "calendar", "payments"],
    keywords: ["proiect", "proiecte", "pipeline", "etapă", "livrare"],
    suggestedQuestions: [
      "Cum creez proiect din contract?",
      "Ce înseamnă etapele?",
    ],
    suggestedQuestionsEn: [
      "How do I create a project from a contract?",
      "What do stages mean?",
    ],
    planFeatures: ["productionPipeline"],
  },
  {
    key: "tasks",
    title: "Task-uri",
    titleEn: "Tasks",
    route: "/dashboard/tasks",
    description: "Sarcini alocate pe proiect/eveniment, cu prioritate și termen.",
    descriptionEn: "Tasks assigned to project/event with priority and due date.",
    actions: ["Creează task", "Asignează coleg", "Marchează finalizat"],
    actionsEn: ["Create task", "Assign teammate", "Mark done"],
    permissions: ["tasks.write", "tasks.delete"],
    relatedModules: ["projects", "calendar", "team"],
    keywords: ["task", "task-uri", "sarcină", "asignează", "deadline"],
    suggestedQuestions: ["Cum creez un task?", "Cum asignez unui coleg?"],
    suggestedQuestionsEn: ["How do I create a task?", "How do I assign a teammate?"],
  },
  {
    key: "payments",
    title: "Plăți",
    titleEn: "Payments",
    route: "/dashboard/payments",
    description: "Avansuri, tranșe, restante și remindere legate de contract/eveniment.",
    descriptionEn: "Deposits, installments, overdue amounts, and reminders.",
    actions: ["Adaugă plată", "Marchează încasat", "Urmărește restante"],
    actionsEn: ["Add payment", "Mark received", "Track overdue"],
    permissions: ["payments.write", "payments.delete"],
    relatedModules: ["contracts", "clients", "automations"],
    keywords: ["plată", "plăți", "avans", "tranșă", "restant", "încasare"],
    suggestedQuestions: ["Cum adaug o plată?", "Cum urmăresc avansul?"],
    suggestedQuestionsEn: ["How do I add a payment?", "How do I track the deposit?"],
  },
  {
    key: "automations",
    title: "Automatizări",
    titleEn: "Automations",
    route: "/dashboard/automations",
    description:
      "Reguli trigger → condiții → acțiuni (task, reminder, follow-up). Disponibile pe planurile Studio și Agency.",
    descriptionEn:
      "Trigger → conditions → actions. Available on Studio and Agency plans.",
    actions: ["Creează automatizare", "Alege trigger", "Configurează acțiuni", "Activează/dezactivează"],
    actionsEn: ["Create automation", "Pick trigger", "Configure actions", "Enable/disable"],
    permissions: ["automations.manage"],
    relatedModules: ["leads", "proposals", "contracts", "payments"],
    keywords: ["automatizare", "trigger", "acțiune", "follow-up", "reminder"],
    suggestedQuestions: [
      "Ce este un trigger?",
      "Cum creez o automatizare?",
      "Ce acțiuni sunt disponibile?",
    ],
    suggestedQuestionsEn: [
      "What is a trigger?",
      "How do I create an automation?",
      "What actions are available?",
    ],
    planFeatures: ["automations"],
  },
  {
    key: "templates",
    title: "Template-uri",
    titleEn: "Templates",
    route: "/dashboard/templates",
    description: "Template-uri de ofertă, contract, email și task-uri reutilizabile.",
    descriptionEn: "Reusable proposal, contract, email, and task templates.",
    actions: ["Creează template", "Editează template", "Folosește la ofertă/contract"],
    actionsEn: ["Create template", "Edit template", "Use in proposal/contract"],
    permissions: ["templates.write"],
    relatedModules: ["proposals", "contracts"],
    keywords: ["template", "template-uri", "șablon", "model"],
    suggestedQuestions: ["Unde găsesc template-urile?", "Cum creez un template de contract?"],
    suggestedQuestionsEn: ["Where are templates?", "How do I create a contract template?"],
  },
  {
    key: "team",
    title: "Echipă",
    titleEn: "Team",
    route: "/dashboard/team",
    description: "Invită colegi, gestionează roluri și accesul în workspace.",
    descriptionEn: "Invite teammates and manage workspace roles.",
    actions: ["Invită coleg", "Schimbă rol", "Revocă acces"],
    actionsEn: ["Invite teammate", "Change role", "Revoke access"],
    permissions: ["members.manage"],
    relatedModules: ["settings", "billing"],
    keywords: ["echipă", "team", "invită", "rol", "coleg", "membru"],
    suggestedQuestions: ["Cum invit un coleg?", "Ce poate face rolul sales?"],
    suggestedQuestionsEn: ["How do I invite a teammate?", "What can the sales role do?"],
  },
  {
    key: "analytics",
    title: "Analytics",
    titleEn: "Analytics",
    route: "/dashboard/analytics",
    description:
      "Conversie, pipeline, venit și surse. Disponibil pe planurile Studio și Agency.",
    descriptionEn: "Conversion, pipeline, revenue, and sources. Studio and Agency plans.",
    actions: ["Vezi conversia", "Analizează sursele", "Urmărește venitul"],
    actionsEn: ["View conversion", "Analyze sources", "Track revenue"],
    permissions: ["analytics.read"],
    relatedModules: ["leads", "payments", "proposals"],
    keywords: ["analytics", "raport", "conversie", "venit", "surse"],
    suggestedQuestions: ["Unde văd analytics?", "Ce indicatori am?"],
    suggestedQuestionsEn: ["Where is analytics?", "What metrics do I get?"],
    planFeatures: ["analytics"],
  },
  {
    key: "settings",
    title: "Setări",
    titleEn: "Settings",
    route: "/dashboard/settings",
    description: "Setări workspace: profil business, preferințe și legături către billing.",
    descriptionEn: "Workspace settings: business profile, preferences, and billing.",
    actions: ["Actualizează profilul", "Deschide billing"],
    actionsEn: ["Update profile", "Open billing"],
    permissions: ["workspace.manage", "billing.read"],
    relatedModules: ["billing", "team"],
    keywords: ["setări", "settings", "profil", "workspace"],
    suggestedQuestions: ["Ce pot configura aici?", "Cum schimb planul?"],
    suggestedQuestionsEn: ["What can I configure here?", "How do I change plan?"],
  },
  {
    key: "billing",
    title: "Billing",
    titleEn: "Billing",
    route: "/dashboard/settings/billing",
    description: "Planul curent (Free/Solo/Studio/Agency), upgrade și limite de utilizare.",
    descriptionEn: "Current plan (Free/Solo/Studio/Agency), upgrades, and usage limits.",
    actions: ["Vezi planul", "Schimbă planul", "Vezi limitele"],
    actionsEn: ["View plan", "Change plan", "View limits"],
    permissions: ["billing.read"],
    relatedModules: ["settings", "team", "automations", "analytics"],
    keywords: ["billing", "plan", "abonament", "upgrade", "preț", "free", "solo"],
    suggestedQuestions: ["Cum schimb planul?", "Ce include Studio?"],
    suggestedQuestionsEn: ["How do I change plan?", "What does Studio include?"],
  },
];
