import type { RoleGuide } from "@/lib/assistant/knowledge/types";

export const ROLE_GUIDES: RoleGuide[] = [
  {
    role: "owner",
    summary: "Control complet asupra workspace-ului, inclusiv billing și membri.",
    summaryEn: "Full workspace control including billing and members.",
    can: ["Toate acțiunile CRM, vânzări, operațiuni, echipă, billing"],
    canEn: ["All CRM, sales, ops, team, billing actions"],
    cannot: [],
    cannotEn: [],
  },
  {
    role: "admin",
    summary: "Aceleași drepturi operaționale ca owner în workspace.",
    summaryEn: "Same operational rights as owner in the workspace.",
    can: ["Toate acțiunile din workspace"],
    canEn: ["All workspace actions"],
    cannot: [],
    cannotEn: [],
  },
  {
    role: "manager",
    summary: "Conduce operațiunile; nu gestionează membrii sau setările critice de workspace.",
    summaryEn: "Runs operations; cannot manage members or critical workspace settings.",
    can: ["CRM write/delete", "Oferte", "Contracte (fără delete)", "Proiecte", "Automatizări"],
    canEn: ["CRM write/delete", "Proposals", "Contracts (no delete)", "Projects", "Automations"],
    cannot: ["Ștergere contracte/plăți", "Gestionare membri", "workspace.manage"],
    cannotEn: ["Delete contracts/payments", "Manage members", "workspace.manage"],
  },
  {
    role: "sales",
    summary: "Focus pe leaduri, oferte, plăți și follow-up — fără ștergeri CRM/contracte.",
    summaryEn: "Leads, proposals, payments, follow-up — no CRM/contract deletes.",
    can: ["crm.write", "proposals.write", "payments.write", "tasks.write", "analytics.read"],
    canEn: ["crm.write", "proposals.write", "payments.write", "tasks.write", "analytics.read"],
    cannot: ["crm.delete", "contracts.write", "projects.write", "members.manage", "automations.manage"],
    cannotEn: ["crm.delete", "contracts.write", "projects.write", "members.manage", "automations.manage"],
  },
  {
    role: "editor",
    summary: "Lucrează pe proiecte, calendar și task-uri; CRM doar în citire.",
    summaryEn: "Projects, calendar, tasks; CRM read-only.",
    can: ["projects.write", "tasks.write", "calendar.write", "crm.read"],
    canEn: ["projects.write", "tasks.write", "calendar.write", "crm.read"],
    cannot: ["crm.write", "proposals.write", "contracts.write", "payments.write"],
    cannotEn: ["crm.write", "proposals.write", "contracts.write", "payments.write"],
  },
  {
    role: "collaborator",
    summary: "Acces limitat: citire CRM + task-uri.",
    summaryEn: "Limited: CRM read + tasks.",
    can: ["crm.read", "tasks.write", "billing.read"],
    canEn: ["crm.read", "tasks.write", "billing.read"],
    cannot: ["Ștergeri", "Oferte/contracte", "Invitații echipă"],
    cannotEn: ["Deletes", "Proposals/contracts", "Team invites"],
  },
  {
    role: "viewer",
    summary: "Doar citire: CRM, analytics, billing.",
    summaryEn: "Read-only: CRM, analytics, billing.",
    can: ["crm.read", "analytics.read", "billing.read"],
    canEn: ["crm.read", "analytics.read", "billing.read"],
    cannot: ["Orice scriere sau ștergere"],
    cannotEn: ["Any write or delete"],
  },
];
