export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          avatar_url: string | null;
          onboarding_completed: boolean;
          account_status: string;
          suspended_at: string | null;
          is_platform_admin: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          avatar_url?: string | null;
          onboarding_completed?: boolean;
          account_status?: string;
          suspended_at?: string | null;
          is_platform_admin?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          onboarding_completed?: boolean;
          account_status?: string;
          suspended_at?: string | null;
          is_platform_admin?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      workspaces: {
        Row: {
          id: string;
          name: string;
          slug: string;
          activity_type: string | null;
          city: string | null;
          country: string | null;
          currency: string;
          timezone: string;
          services: string[] | null;
          events_per_year: number | null;
          team_size: string | null;
          logo_url: string | null;
          brand_primary: string | null;
          brand_accent: string | null;
          fiscal_data: Json | null;
          settings: Json | null;
          plan: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          activity_type?: string | null;
          city?: string | null;
          country?: string | null;
          currency?: string;
          timezone?: string;
          services?: string[] | null;
          events_per_year?: number | null;
          team_size?: string | null;
          logo_url?: string | null;
          brand_primary?: string | null;
          brand_accent?: string | null;
          fiscal_data?: Json | null;
          settings?: Json | null;
          plan?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["workspaces"]["Insert"]>;
        Relationships: [];
      };
      workspace_members: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          role: string;
          disabled_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          role: string;
          disabled_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          role?: string;
          disabled_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      leads: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          email: string | null;
          phone: string | null;
          event_type: string | null;
          event_date: string | null;
          city: string | null;
          venue: string | null;
          budget: number | null;
          currency: string;
          source: string | null;
          services: string[] | null;
          notes: string | null;
          owner_id: string | null;
          created_by: string | null;
          status: string;
          estimated_value: number | null;
          follow_up_date: string | null;
          tags: string[] | null;
          lost_reason: string | null;
          client_id: string | null;
          converted_at: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          email?: string | null;
          phone?: string | null;
          event_type?: string | null;
          event_date?: string | null;
          city?: string | null;
          venue?: string | null;
          budget?: number | null;
          currency?: string;
          source?: string | null;
          services?: string[] | null;
          notes?: string | null;
          owner_id?: string | null;
          created_by?: string | null;
          status?: string;
          estimated_value?: number | null;
          follow_up_date?: string | null;
          tags?: string[] | null;
          lost_reason?: string | null;
          client_id?: string | null;
          converted_at?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["leads"]["Insert"]>;
        Relationships: [];
      };
      clients: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          email: string | null;
          phone: string | null;
          company: string | null;
          address: string | null;
          city: string | null;
          country: string | null;
          event_date: string | null;
          event_type: string | null;
          status: string;
          total_value: number | null;
          notes: string | null;
          tags: string[] | null;
          source: string | null;
          lead_id: string | null;
          created_by: string | null;
          portal_token: string | null;
          deleted_at: string | null;
          archived_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          email?: string | null;
          phone?: string | null;
          company?: string | null;
          address?: string | null;
          city?: string | null;
          country?: string | null;
          event_date?: string | null;
          event_type?: string | null;
          status?: string;
          total_value?: number | null;
          notes?: string | null;
          tags?: string[] | null;
          source?: string | null;
          lead_id?: string | null;
          created_by?: string | null;
          portal_token?: string | null;
          deleted_at?: string | null;
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["clients"]["Insert"]>;
        Relationships: [];
      };
      proposals: {
        Row: {
          id: string;
          workspace_id: string;
          client_id: string | null;
          lead_id: string | null;
          proposal_number: string | null;
          title: string;
          package_name: string | null;
          amount: number;
          currency: string;
          subtotal: number;
          discount_type: string;
          discount_value: number;
          discount_amount: number;
          tax_rate: number;
          tax_amount: number;
          total: number;
          status: string;
          valid_until: string | null;
          public_token: string;
          public_token_expires_at: string | null;
          viewed_at: string | null;
          accepted_at: string | null;
          rejected_at: string | null;
          cancelled_at: string | null;
          created_by: string | null;
          deleted_at: string | null;
          notes: string | null;
          terms: string | null;
          metadata: Json | null;
          snapshot: Json | null;
          acceptance: Json | null;
          rejection_reason: string | null;
          contract_id: string | null;
          content: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          client_id?: string | null;
          lead_id?: string | null;
          proposal_number?: string | null;
          title: string;
          package_name?: string | null;
          amount?: number;
          currency?: string;
          subtotal?: number;
          discount_type?: string;
          discount_value?: number;
          discount_amount?: number;
          tax_rate?: number;
          tax_amount?: number;
          total?: number;
          status?: string;
          valid_until?: string | null;
          public_token?: string;
          public_token_expires_at?: string | null;
          viewed_at?: string | null;
          accepted_at?: string | null;
          rejected_at?: string | null;
          cancelled_at?: string | null;
          created_by?: string | null;
          deleted_at?: string | null;
          notes?: string | null;
          terms?: string | null;
          metadata?: Json | null;
          snapshot?: Json | null;
          acceptance?: Json | null;
          rejection_reason?: string | null;
          contract_id?: string | null;
          content?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["proposals"]["Insert"]>;
        Relationships: [];
      };
      proposal_items: {
        Row: {
          id: string;
          workspace_id: string;
          proposal_id: string;
          name: string;
          description: string | null;
          quantity: number;
          unit_price: number;
          discount: number;
          tax_rate: number;
          line_total: number;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          proposal_id: string;
          name: string;
          description?: string | null;
          quantity?: number;
          unit_price?: number;
          discount?: number;
          tax_rate?: number;
          line_total?: number;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["proposal_items"]["Insert"]>;
        Relationships: [];
      };
      contracts: {
        Row: {
          id: string;
          workspace_id: string;
          client_id: string | null;
          lead_id: string | null;
          proposal_id: string | null;
          contract_number: string | null;
          title: string;
          amount: number;
          deposit: number;
          status: string;
          currency: string;
          subtotal: number;
          discount_amount: number;
          tax_amount: number;
          total: number;
          deposit_amount: number;
          remaining_amount: number;
          signed_at: string | null;
          signer_name: string | null;
          signer_ip: string | null;
          event_date: string | null;
          event_location: string | null;
          valid_from: string | null;
          valid_until: string | null;
          public_token: string | null;
          public_token_hash: string | null;
          public_token_expires_at: string | null;
          published_at: string | null;
          viewed_at: string | null;
          accepted_at: string | null;
          cancelled_at: string | null;
          created_by: string | null;
          content: Json | null;
          terms: string | null;
          snapshot: Json | null;
          acceptance: Json | null;
          contract_content_hash: string | null;
          previous_contract_id: string | null;
          template_id: string | null;
          metadata: Json | null;
          version: number;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          archived_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          client_id?: string | null;
          lead_id?: string | null;
          proposal_id?: string | null;
          contract_number?: string | null;
          title: string;
          amount?: number;
          deposit?: number;
          status?: string;
          currency?: string;
          subtotal?: number;
          discount_amount?: number;
          tax_amount?: number;
          total?: number;
          deposit_amount?: number;
          remaining_amount?: number;
          signed_at?: string | null;
          signer_name?: string | null;
          signer_ip?: string | null;
          event_date?: string | null;
          event_location?: string | null;
          valid_from?: string | null;
          valid_until?: string | null;
          public_token?: string | null;
          public_token_hash?: string | null;
          public_token_expires_at?: string | null;
          published_at?: string | null;
          viewed_at?: string | null;
          accepted_at?: string | null;
          cancelled_at?: string | null;
          created_by?: string | null;
          content?: Json | null;
          terms?: string | null;
          snapshot?: Json | null;
          acceptance?: Json | null;
          contract_content_hash?: string | null;
          previous_contract_id?: string | null;
          template_id?: string | null;
          metadata?: Json | null;
          version?: number;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          archived_at?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["contracts"]["Insert"]>;
        Relationships: [];
      };
      contract_templates: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          category: string;
          content: Json;
          terms: string | null;
          variables: string[] | null;
          is_default: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          category?: string;
          content?: Json;
          terms?: string | null;
          variables?: string[] | null;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["contract_templates"]["Insert"]>;
        Relationships: [];
      };
      client_portal_tokens: {
        Row: {
          id: string;
          workspace_id: string;
          client_id: string;
          token_hash: string;
          expires_at: string | null;
          revoked_at: string | null;
          last_accessed_at: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          client_id: string;
          token_hash: string;
          expires_at?: string | null;
          revoked_at?: string | null;
          last_accessed_at?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["client_portal_tokens"]["Insert"]>;
        Relationships: [];
      };
      projects: {
        Row: {
          id: string;
          workspace_id: string;
          client_id: string | null;
          proposal_id: string | null;
          contract_id: string | null;
          name: string;
          event_date: string | null;
          status: string;
          deadline: string | null;
          progress: number;
          team: string[] | null;
          pipeline_key: string;
          location: string | null;
          notes: string | null;
          documents: Json;
          budget: number;
          cost: number;
          estimated_revenue: number;
          currency: string;
          created_by: string | null;
          archived_at: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          client_id?: string | null;
          proposal_id?: string | null;
          contract_id?: string | null;
          name: string;
          event_date?: string | null;
          status?: string;
          deadline?: string | null;
          progress?: number;
          team?: string[] | null;
          pipeline_key?: string;
          location?: string | null;
          notes?: string | null;
          documents?: Json;
          budget?: number;
          cost?: number;
          estimated_revenue?: number;
          currency?: string;
          created_by?: string | null;
          archived_at?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["projects"]["Insert"]>;
        Relationships: [];
      };
      tasks: {
        Row: {
          id: string;
          workspace_id: string;
          project_id: string | null;
          client_id: string | null;
          calendar_event_id: string | null;
          title: string;
          due_date: string | null;
          priority: string;
          status: string;
          assignee_id: string | null;
          notes: string | null;
          subtasks: Json;
          completed_at: string | null;
          created_by: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          project_id?: string | null;
          client_id?: string | null;
          calendar_event_id?: string | null;
          title: string;
          due_date?: string | null;
          priority?: string;
          status?: string;
          assignee_id?: string | null;
          notes?: string | null;
          subtasks?: Json;
          completed_at?: string | null;
          created_by?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["tasks"]["Insert"]>;
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          workspace_id: string;
          client_id: string | null;
          contract_id: string | null;
          project_id: string | null;
          label: string;
          amount: number;
          paid_amount: number;
          due_date: string | null;
          method: string | null;
          status: string;
          reference: string | null;
          notes: string | null;
          proof_url: string | null;
          currency: string;
          paid_at: string | null;
          cancelled_at: string | null;
          created_by: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          client_id?: string | null;
          contract_id?: string | null;
          project_id?: string | null;
          label: string;
          amount?: number;
          paid_amount?: number;
          due_date?: string | null;
          method?: string | null;
          status?: string;
          reference?: string | null;
          notes?: string | null;
          proof_url?: string | null;
          currency?: string;
          paid_at?: string | null;
          cancelled_at?: string | null;
          created_by?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["payments"]["Insert"]>;
        Relationships: [];
      };
      calendar_events: {
        Row: {
          id: string;
          workspace_id: string;
          title: string;
          description: string | null;
          event_type: string;
          starts_at: string;
          ends_at: string;
          all_day: boolean;
          location: string | null;
          client_id: string | null;
          project_id: string | null;
          contract_id: string | null;
          member_ids: string[];
          color: string | null;
          status: string;
          notes: string | null;
          reminder_at: string | null;
          recurrence: Json | null;
          created_by: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          title: string;
          description?: string | null;
          event_type?: string;
          starts_at: string;
          ends_at: string;
          all_day?: boolean;
          location?: string | null;
          client_id?: string | null;
          project_id?: string | null;
          contract_id?: string | null;
          member_ids?: string[];
          color?: string | null;
          status?: string;
          notes?: string | null;
          reminder_at?: string | null;
          recurrence?: Json | null;
          created_by?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["calendar_events"]["Insert"]>;
        Relationships: [];
      };
      automations: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          description: string | null;
          trigger_key: string;
          channel: string;
          enabled: boolean;
          config: Json | null;
          conditions: Json;
          actions: Json;
          last_run_at: string | null;
          created_by: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          description?: string | null;
          trigger_key: string;
          channel?: string;
          enabled?: boolean;
          config?: Json | null;
          conditions?: Json;
          actions?: Json;
          last_run_at?: string | null;
          created_by?: string | null;
          deleted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["automations"]["Insert"]>;
        Relationships: [];
      };
      automation_runs: {
        Row: {
          id: string;
          automation_id: string;
          workspace_id: string;
          trigger_key: string;
          status: string;
          started_at: string;
          finished_at: string | null;
          error: string | null;
          metadata: Json;
          idempotency_key: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          automation_id: string;
          workspace_id: string;
          trigger_key: string;
          status?: string;
          started_at?: string;
          finished_at?: string | null;
          error?: string | null;
          metadata?: Json;
          idempotency_key: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["automation_runs"]["Insert"]>;
        Relationships: [];
      };
      workspace_templates: {
        Row: {
          id: string;
          workspace_id: string;
          type: string;
          name: string;
          category: string;
          business_type: string | null;
          content: Json;
          variables: string[];
          is_default: boolean;
          archived_at: string | null;
          deleted_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          type: string;
          name: string;
          category?: string;
          business_type?: string | null;
          content?: Json;
          variables?: string[];
          is_default?: boolean;
          archived_at?: string | null;
          deleted_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["workspace_templates"]["Insert"]>;
        Relationships: [];
      };
      workspace_invitations: {
        Row: {
          id: string;
          workspace_id: string;
          email: string;
          role: string;
          token_hash: string;
          expires_at: string;
          accepted_at: string | null;
          revoked_at: string | null;
          invited_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          email: string;
          role: string;
          token_hash: string;
          expires_at: string;
          accepted_at?: string | null;
          revoked_at?: string | null;
          invited_by?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["workspace_invitations"]["Insert"]>;
        Relationships: [];
      };
      activity_logs: {
        Row: {
          id: string;
          workspace_id: string;
          actor_id: string | null;
          entity_type: string;
          entity_id: string | null;
          action: string | null;
          title: string;
          description: string | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          actor_id?: string | null;
          entity_type: string;
          entity_id?: string | null;
          action?: string | null;
          title: string;
          description?: string | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["activity_logs"]["Insert"]>;
        Relationships: [];
      };
      subscriptions: {
        Row: {
          id: string;
          workspace_id: string;
          plan: string;
          status: string;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          stripe_price_id: string | null;
          trial_ends_at: string | null;
          current_period_start: string | null;
          current_period_end: string | null;
          cancel_at_period_end: boolean;
          trial_end: string | null;
          billing_interval: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          plan?: string;
          status?: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          stripe_price_id?: string | null;
          trial_ends_at?: string | null;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          trial_end?: string | null;
          billing_interval?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["subscriptions"]["Insert"]>;
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          type: string;
          title: string;
          body: string | null;
          entity_type: string | null;
          entity_id: string | null;
          action_url: string | null;
          read_at: string | null;
          idempotency_key: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          type: string;
          title: string;
          body?: string | null;
          entity_type?: string | null;
          entity_id?: string | null;
          action_url?: string | null;
          read_at?: string | null;
          idempotency_key?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["notifications"]["Insert"]>;
        Relationships: [];
      };
      cron_runs: {
        Row: {
          id: string;
          job: string;
          started_at: string;
          finished_at: string | null;
          duration_ms: number | null;
          success: boolean;
          processed: number;
          errors: number;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          job: string;
          started_at?: string;
          finished_at?: string | null;
          duration_ms?: number | null;
          success?: boolean;
          processed?: number;
          errors?: number;
          metadata?: Json;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["cron_runs"]["Insert"]>;
        Relationships: [];
      };
      workspace_statistics: {
        Row: {
          workspace_id: string;
          snapshot_date: string;
          leads_count: number;
          leads_won_count: number;
          conversion_rate: number | null;
          contracts_count: number;
          contracts_accepted_count: number;
          revenue_by_currency: Json;
          outstanding_by_currency: Json;
          overdue_payments_count: number;
          active_projects_count: number;
          overdue_tasks_count: number;
          upcoming_events_count: number;
          metadata: Json;
          computed_at: string;
          updated_at: string;
        };
        Insert: {
          workspace_id: string;
          snapshot_date?: string;
          leads_count?: number;
          leads_won_count?: number;
          conversion_rate?: number | null;
          contracts_count?: number;
          contracts_accepted_count?: number;
          revenue_by_currency?: Json;
          outstanding_by_currency?: Json;
          overdue_payments_count?: number;
          active_projects_count?: number;
          overdue_tasks_count?: number;
          upcoming_events_count?: number;
          metadata?: Json;
          computed_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["workspace_statistics"]["Insert"]>;
        Relationships: [];
      };
      email_deliveries: {
        Row: {
          id: string;
          workspace_id: string | null;
          recipient: string;
          template: string;
          entity_type: string | null;
          entity_id: string | null;
          provider_message_id: string | null;
          status: string;
          sent_at: string | null;
          failed_at: string | null;
          error_code: string | null;
          error_message: string | null;
          idempotency_key: string;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id?: string | null;
          recipient: string;
          template: string;
          entity_type?: string | null;
          entity_id?: string | null;
          provider_message_id?: string | null;
          status?: string;
          sent_at?: string | null;
          failed_at?: string | null;
          error_code?: string | null;
          error_message?: string | null;
          idempotency_key: string;
          metadata?: Json;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["email_deliveries"]["Insert"]>;
        Relationships: [];
      };
      user_feedback: {
        Row: {
          id: string;
          workspace_id: string | null;
          user_id: string | null;
          type: string;
          message: string;
          rating: number | null;
          page_url: string | null;
          status: string;
          priority: string | null;
          assigned_to: string | null;
          admin_notes: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id?: string | null;
          user_id?: string | null;
          type: string;
          message: string;
          rating?: number | null;
          page_url?: string | null;
          status?: string;
          priority?: string | null;
          assigned_to?: string | null;
          admin_notes?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["user_feedback"]["Insert"]>;
        Relationships: [];
      };
      stripe_webhook_events: {
        Row: {
          id: string;
          type: string;
          processed_at: string;
          payload_summary: Json;
        };
        Insert: {
          id: string;
          type: string;
          processed_at?: string;
          payload_summary?: Json;
        };
        Update: Partial<Database["public"]["Tables"]["stripe_webhook_events"]["Insert"]>;
        Relationships: [];
      };
      platform_admins: {
        Row: {
          user_id: string;
          role: string;
          disabled_at: string | null;
          invited_by: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          role: string;
          disabled_at?: string | null;
          invited_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["platform_admins"]["Insert"]>;
        Relationships: [];
      };
      platform_audit_logs: {
        Row: {
          id: string;
          actor_id: string | null;
          action: string;
          entity_type: string | null;
          entity_id: string | null;
          reason: string | null;
          metadata: Json;
          ip: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          actor_id?: string | null;
          action: string;
          entity_type?: string | null;
          entity_id?: string | null;
          reason?: string | null;
          metadata?: Json;
          ip?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["platform_audit_logs"]["Insert"]>;
        Relationships: [];
      };
      admin_access_logs: {
        Row: {
          id: string;
          user_id: string | null;
          path: string;
          outcome: string;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          path: string;
          outcome: string;
          metadata?: Json;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["admin_access_logs"]["Insert"]>;
        Relationships: [];
      };
      admin_inspect_sessions: {
        Row: {
          id: string;
          admin_id: string;
          workspace_id: string;
          reason: string;
          expires_at: string;
          ended_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          admin_id: string;
          workspace_id: string;
          reason: string;
          expires_at: string;
          ended_at?: string | null;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["admin_inspect_sessions"]["Insert"]>;
        Relationships: [];
      };
      plans: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string;
          currency: string;
          visible: boolean;
          active: boolean;
          highlighted: boolean;
          sort_order: number;
          visibility: string;
          cta: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          slug: string;
          description?: string;
          currency?: string;
          visible?: boolean;
          active?: boolean;
          highlighted?: boolean;
          sort_order?: number;
          visibility?: string;
          cta?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["plans"]["Insert"]>;
        Relationships: [];
      };
      plan_versions: {
        Row: {
          id: string;
          plan_id: string;
          version: number;
          price_monthly: number;
          price_yearly: number | null;
          stripe_price_monthly_id: string | null;
          stripe_price_yearly_id: string | null;
          trial_days: number;
          limits: Json;
          features: Json;
          is_current: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          plan_id: string;
          version: number;
          price_monthly?: number;
          price_yearly?: number | null;
          stripe_price_monthly_id?: string | null;
          stripe_price_yearly_id?: string | null;
          trial_days?: number;
          limits?: Json;
          features?: Json;
          is_current?: boolean;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["plan_versions"]["Insert"]>;
        Relationships: [];
      };
      platform_settings: {
        Row: {
          key: string;
          value: Json;
          updated_by: string | null;
          updated_at: string;
        };
        Insert: {
          key: string;
          value?: Json;
          updated_by?: string | null;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["platform_settings"]["Insert"]>;
        Relationships: [];
      };
      system_errors: {
        Row: {
          id: string;
          severity: string;
          module: string;
          route: string | null;
          message: string;
          error_type: string | null;
          stack: string | null;
          workspace_id: string | null;
          user_id: string | null;
          occurrence_count: number;
          first_seen_at: string;
          last_seen_at: string;
          resolved_at: string | null;
          resolved_by: string | null;
          notes: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          severity?: string;
          module: string;
          route?: string | null;
          message: string;
          error_type?: string | null;
          stack?: string | null;
          workspace_id?: string | null;
          user_id?: string | null;
          occurrence_count?: number;
          first_seen_at?: string;
          last_seen_at?: string;
          resolved_at?: string | null;
          resolved_by?: string | null;
          notes?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["system_errors"]["Insert"]>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      is_platform_admin: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      get_platform_admin_role: {
        Args: Record<string, never>;
        Returns: string;
      };
      is_workspace_member: {
        Args: { p_workspace_id: string };
        Returns: boolean;
      };
      ensure_own_profile: {
        Args: Record<string, never>;
        Returns: undefined;
      };
      create_onboarding_workspace: {
        Args: {
          p_name: string;
          p_activity_type: string;
          p_city: string;
          p_country: string;
          p_services?: string[];
          p_events_per_year?: number | null;
          p_team_size?: string | null;
          p_currency?: string;
          p_timezone?: string;
          p_logo_url?: string | null;
          p_brand_accent?: string | null;
          p_fiscal_data?: Json | null;
          p_settings?: Json | null;
        };
        Returns: string;
      };
      convert_lead_to_client: {
        Args: {
          p_lead_id: string;
          p_existing_client_id?: string | null;
        };
        Returns: string;
      };
      get_proposal_by_token: {
        Args: { p_token: string };
        Returns: Database["public"]["Tables"]["proposals"]["Row"][];
      };
      get_public_proposal_by_token: {
        Args: { p_token: string };
        Returns: Json;
      };
      mark_proposal_viewed_by_token: {
        Args: { p_token: string };
        Returns: Json;
      };
      accept_proposal_by_token: {
        Args: {
          p_token: string;
          p_full_name: string;
          p_email: string;
          p_accepted_terms: boolean;
          p_ip?: string | null;
          p_user_agent?: string | null;
        };
        Returns: Json;
      };
      reject_proposal_by_token: {
        Args: { p_token: string; p_reason?: string | null };
        Returns: Json;
      };
      next_proposal_number: {
        Args: { p_workspace_id: string };
        Returns: string;
      };
      next_contract_number: {
        Args: { p_workspace_id: string };
        Returns: string;
      };
      hash_token: {
        Args: { p_token: string };
        Returns: string;
      };
      create_contract_from_proposal: {
        Args: { p_proposal_id: string };
        Returns: string;
      };
      get_public_contract_by_token: {
        Args: { p_token: string };
        Returns: Json;
      };
      mark_contract_viewed_by_token: {
        Args: { p_token: string };
        Returns: Json;
      };
      accept_contract_by_token: {
        Args: {
          p_token: string;
          p_full_name: string;
          p_email: string;
          p_accepted_terms: boolean;
          p_accepted_privacy?: boolean;
          p_document_hash?: string | null;
          p_ip?: string | null;
          p_user_agent?: string | null;
        };
        Returns: Json;
      };
      get_client_portal_by_token: {
        Args: { p_token: string };
        Returns: Json;
      };
      get_client_by_portal_token: {
        Args: { p_token: string };
        Returns: Database["public"]["Tables"]["clients"]["Row"][];
      };
      contract_payment_totals: {
        Args: { p_workspace_id: string; p_contract_id: string };
        Returns: Json;
      };
      workspace_analytics_summary: {
        Args: {
          p_workspace_id: string;
          p_from?: string | null;
          p_to?: string | null;
        };
        Returns: Json;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
